name: sakupay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Cloud Services
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # AI & Environment
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.1
  uuid: ^4.4.0

  # UI & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/flutter_launcher_icons.png"
  min_sdk_android: 21