name: sakupay
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Cloud Services
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1  # Untuk login dengan akun Google

  # UI & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0            # Untuk format tanggal, mata uang, dsb
  flutter_staggered_animations: ^1.1.1  # Untuk animasi kartu game

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_sakupay.png       # Logo utama aplikasi
    - assets/google_logo.png        # Logo Google untuk tombol login
